switch to on push event

diff --git a/.github/workflows/post-merge.yml b/.github/workflows/post-merge.yml
--- a/.github/workflows/post-merge.yml
+++ b/.github/workflows/post-merge.yml
@@ -1,15 +1,71 @@
-name: Trigger Post Merge Jobs
+name: Update cards and screenshots
 
 on:
-  pull_request:
-    types: [closed]
-    branches: [master]
+  push:
+    branches:
+      - master
+env:
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  SKIP_REST: false
 
 jobs:
-  kickoff-post-merge:
-    if: github.event.pull_request.merged == true
+  update-cards-and-screenshots:
     runs-on: ubuntu-latest
+    # Don't push changes to main branches in forks as this causes merge conflicts
+    if: ${{ !github.event.repository.fork }}
+    permissions:
+      contents: write
+    # running two copies of this job at once can create race conditions
+    # and will usually cause the most recent workflow to fail. It is
+    # preferable to always have the most up to date workflow succeed
+    # so we cancel this job whenever a newer one is started.
+    concurrency:
+      group: post-merge
+      cancel-in-progress: true
     steps:
       - uses: actions/checkout@v4
-      - name: Run Post Merge Jobs
-        uses: ./.github/workflows/update-cards.yml
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: 'npm'
+
+      - name: Install job dependencies
+        run: npm install
+
+      - name: Configure Git
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+      - name: Generate cards.json
+        run: node generators/generateCards.js
+
+      - name: Check for cards changes
+        run: |
+          if git diff --quiet public/cards.json; then
+            echo "No changes to commit"
+            echo "SKIP_REST=true" >> $GITHUB_ENV
+          else
+            git add public/cards.json
+            git commit -m "(CI) cards.json Generation"
+          fi
+      - name: Format cards
+        if: env.SKIP_REST != 'true'
+        run: |
+          if [ ! -f .prettierrc ]; then
+            echo ".prettierrc not found"
+            echo "terminating workflow..."
+            exit 1;
+          fi
+          npx prettier public/cards.json --write
+          git add public/cards.json
+          git commit -m "(CI) Format cards" || echo "No changes to commit"
+      - name: Generate screenshots
+        if: env.SKIP_REST != 'true'
+        run: |
+          node generators/generateScreenshot.js
+          git add Art/**/icon.png
+          git commit -m "(CI) Screenshot Generation" || echo "No changes to commit"
+      - name: Push changes
+        if: env.SKIP_REST != 'true'
+        run: git push origin master
